language: node_js

os:
  - linux

install:
  - npm install

node_js:
  - "6.2.1"
  - "5.0"

before_script:
  - npm run babel-scripts
  - node scripts-babel/module-manage/index.js --update --travis --token $GH_TOKEN
  - node scripts-babel/auto-demo/index.js --travis

script:
  - npm run build

cache:
  directories:
  - node_modules

env:
  - GH_TOKEN=GH_TOKEN