language: node_js

os:
  - linux

install:
  - npm install

node_js:
  - "6.2.1"
  - "5.0"

before_script:
  - rm -rf lib
  - npm run update

script:
  - npm run build

cache:
  directories:
  - node_modules